server:
  port: 8099


spring:
  thymeleaf:
      prefix: classpath:/templates/

  #配置数据源
  datasource:
    druid:
      type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      url: jdbc:log4jdbc:mysql://localhost:3306/alumni?serverTimezone=UTC&characterEncoding=utf8&useSSL=false
      username: root
      password: root

      # 初始化连接大小
      initial-size: 5
      # 最小空闲连接数
      min-idle: 5
      max-active: 20
      max-wait: 30000
      # 可关闭的空闲连接间隔时间
      time-between-eviction-runs-millis: 60000
      # 配置连接在池中的最小生存时间
      min-evictable-idle-time-millis: 300000
      validation-query: select '1' from dual
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的filters
      filters: stat

      web-stat-filter:
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
# Mybatis config
mybatis:
  mapper-locations: classpath:mapper/*.xml

# Redis config
  redis:

  # Redis数据库索引（默认为0）
    database: 0
  # 连接超时时间（毫秒）
    timeout: 0
  # Redis服务器地址
    host: 127.0.0.1
  # Redis服务器连接端口
    port: 6379
  # Redis服务器连接密码（默认为空）
    password:
  # 连接池最大连接数（使用负值表示没有限制）
    pool:
      max-active: 20
  # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
  # 连接池中的最大空闲连接
      max-idle: 300
  # 连接池中的最小空闲连接
      min-idle: 0